//------------------------------------------------------------------------------
// This file is automatically generated by tools/generate-package-versions.js
// Do not edit this file manually
//------------------------------------------------------------------------------
export const packageVersions = {
  nx: '21.6.2',
  firebase: '12.4.0',
  firebaseAdmin: '13.5.0',
  firebaseFunctions: '6.5.0',
  firebaseFunctionsTest: '3.1.1',
  firebaseTools: '14.19.1',
  killPort: '2.0.1',
  nodeEngine: '18',
  googleCloudFunctionsFramework: '4.0.0',
}
